name: msw-server
on:
  push:
    branches:
      - "main"
      - "alpha"
  pull_request:

jobs:
  test:
    name: "node ${{ matrix.node }} ${{matrix.browser}}  ${{ matrix.os }} "
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14, 12, 10]
        browser: ["chrome:headless"] #, "firefox:headless"]
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/checkout@v1
      - run: yarn
      - run: ls node_modules/@graphql-tools/schema
      - run: ls node_modules/graphql
      
      - name: Build
        run: yarn build
      - run: (cd app && yarn)
      # - run: yarn test
      - name: Install TestCafe
        uses: DevExpress/testcafe-action@latest
        with:
          args: '-v'
      - name: Run testcafe
        run:  yarn e2e
  release:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/checkout@v1
      - run: yarn --frozen-lockfile
      - run: yarn build
      - run: ls -asl dist
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
